#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define DLG_MAIN                                100
#define DLG_PROGRESS                            102
#define MENU_MAIN                               104
#define ICON32                                  107
#define ICON16                                  108
#define DLG_OPTIONS                             110
#define FRAMES_SEC                              1001
#define LOG_EDIT                                1001
#define TIME_START                              1002
#define WA_CHAT                                 1004
#define AUDIO_FORMAT_MENU                       1005
#define REPLAY_PATH                             1010
#define AVI_PATH                                1011
#define RES_X                                   1014
#define RES_Y                                   1015
#define REPLAY_BROWSE                           1016
#define AVI_BROWSE                              1017
#define TIME_END                                1018
#define VIDEO_FORMAT                            1020
#define DO_CLEANUP                              1023
#define SELECT_WA_DIR                           40000
#define ADV_OPTIONS                             40001
#define WA_DETAIL                               40002
#define WA_LOCK_CAMERA                          40002
#define WA_BIGGER_FONT                          40003
#define WA_TRANSPARENT_LABELS                   40004
#define LOAD_WORMKIT_DLLS                       40005
#define MAX_ENC_THREADS                         40005
#define INIT_VOL_EDIT                           40006
#define INIT_VOL_SLIDER                         40007
#define STEP_VOL_SLIDER                         40013
#define STEP_VOL_EDIT                           40014
#define MIN_VOL_SLIDER                          40015
#define MIN_VOL_EDIT                            40016
#define FIX_CLIPPING                            40017
